[package]
name = "winit-test"
version = "0.1.0"
edition = "2021"

#[lib]
#name = "main_lib"
#crate-type = ["cdylib"]

[dependencies]
image = "0.25.1"
winit = { version = "^0.29.15", features = ["rwh_06"] }

[target.'cfg(linux)'.dependencies]
#x11 = { version = "^2.21.0", features = ["xlib"] }

[target.'cfg(windows)'.dependencies]
