[package]
name = "lenzu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "^0.28.7", features = ["mint", "serde"] }

# Until prototype is done, we'll allow Windows specific code
#[cfg(target_os = "windows")]
winapi = { version = "^0.3.9", features = ["winuser", "winbase"] }

# Until prototype is done, we'll allow Linux specific code
# For now, we'll just comment X11 out while dev'ing on Windows because this does not work on Windows
#cfg(target_os = "linux")]
#x11 = { version = "^2.21.0", features = ["xlib"] }
