/* automatically generated by rust-bindgen 0.69.5 */

extern "C" {
    pub fn kakasi_getopt_argv(
        argc: ::std::os::raw::c_int,
        argv: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kakasi_do(str_: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn kakasi_close_kanwadict() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn kakasi_free(p: *mut ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn digest_start_copy();
}
extern "C" {
    pub fn put_separator();
}
extern "C" {
    pub fn putchars();
}
extern "C" {
    pub fn digest_out();
}
extern "C" {
    pub fn digest() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn digest_shift();
}
extern "C" {
    pub fn setcharbuffer(s: *mut ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn getpbstr() -> *mut ::std::os::raw::c_char;
}
