[package]
edition = "2021"
name = "lenzu"
version = "0.1.0"

[[bin]]
name = "lenzu"
path = "src/main.rs"

[dependencies]
arboard = "3.4"
base64 = "0.22"
cairo-rs = "0.18"
chrono = "0.4"
gdk = {version = "0.18", features = ["v3_24"]}
gdk-pixbuf = "0.18"
glib = "0.18"
gtk = {version = "0.18", features = ["v3_24"]}
image = {version = "0.25", default-features = false, features = ["png"]}
isolang = {version = "2.4.0", features = ["serde"]}
libc = "0.2.150"
pango = "0.18"
pangocairo = "0.18"
reqwest = {version = "0.12", features = ["blocking", "json"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
x11rb = {version = "0.13", features = ["all-extensions"]}

[dev-dependencies]
tokio = {version = "1.0", features = ["full"]}
wiremock = "0.6"
