pub mod cursor_data;
pub mod interpreter_ja_kakasi;
pub mod interpreter_ja_mecab;
pub mod interpreter_traits;
pub mod ocr_gcloud;
pub mod ocr_tesseract;
pub mod ocr_traits;
pub mod ocr_winmedia;
pub mod image_handling;